# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cace', models.CharField(max_length=128)),
                ('service', models.TextField()),
                ('memo', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('telephone', models.CharField(max_length=128)),
                ('mail', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128)),
                ('host', models.CharField(max_length=128)),
                ('user', models.CharField(default='zabbix', max_length=128)),
                ('passwd', models.CharField(default='zabbix', max_length=128)),
                ('db', models.CharField(default='zabbix', max_length=128)),
                ('port', models.IntegerField(default=3306)),
                ('charset', models.CharField(default='utf8', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('telephone', models.CharField(max_length=128)),
                ('mail', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='cace',
            name='Monitoring_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Database'),
        ),
        migrations.AddField(
            model_name='cace',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company'),
        ),
        migrations.AddField(
            model_name='cace',
            name='sales_main_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_main_staff', to='api.Staff'),
        ),
        migrations.AddField(
            model_name='cace',
            name='sales_sub_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_sub_staff', to='api.Staff'),
        ),
        migrations.AddField(
            model_name='cace',
            name='technical_main_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_main_staff', to='api.Staff'),
        ),
        migrations.AddField(
            model_name='cace',
            name='technical_sub_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_sub_staff', to='api.Staff'),
        ),
    ]
