# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cace', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('mail', models.CharField(max_length=128)),
                ('telephone', models.CharField(max_length=128)),
                ('service', models.TextField()),
                ('main_sales_staff', models.TextField()),
                ('sub_sales_staff', models.TextField()),
                ('main_technical_staff', models.TextField()),
                ('sub_technical_staff', models.TextField()),
                ('memo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=128)),
                ('user', models.CharField(default='zabbix', max_length=128)),
                ('passwd', models.CharField(default='zabbix', max_length=128)),
                ('db', models.CharField(default='zabbix', max_length=128)),
                ('port', models.IntegerField(default=3306)),
                ('charset', models.CharField(default='utf8', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database', to='api.Cace')),
            ],
        ),
    ]
