# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 06:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170725_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cace',
            name='sales_main_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_main_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cace',
            name='sales_sub_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_sub_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cace',
            name='technical_main_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_main_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cace',
            name='technical_sub_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_sub_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
