# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171017_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='columns',
            name='tables',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Tables'),
            preserve_default=False,
        ),
    ]
